# -*- coding: utf-8 -*-
"""ПЕРЕВОД

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qmKQk2n2V5xFlxXh3YUIRau5JwBQiL8
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import json
import pandas as pd
from datasets import Dataset
from datasets import load_dataset
import random
import numpy as np

!pip install transformers==4.28.1

"""# Создание датасета

## Классификационный датасет на русском
"""

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-ru")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-ru")

!wget https://raw.githubusercontent.com/clinc/oos-eval/refs/heads/master/data/data_full.json

# with open('/content/clinc_oos_full.json', 'r', encoding='utf-8') as f:
#     data = json.load(f)

for key in data.keys():
  for item in data[key]:
    if not item["label"]:
      print(item)

with open('data_full.json', 'r', encoding='utf-8') as f:
    data = json.load(f)


new_data = []

for item in data.keys():
  # if item in ['oos_val', 'oos_test', 'oos_train']:
  #   continue
  for i in data[item]:
    if i[1] in {'transfer', 'transactions', 'balance', 'freeze_account', 'pay_bill', 'bill_balance', 'bill_due', 'interest_rate', 'routing_number', 'minimum_payment', 'order_checks', 'pin_change', 'report_fraud', 'account_blocked', 'spending_history', 'credit_score', 'report_lost_card', 'credit_limit', 'rewards_balance', 'new_card', 'application_status', 'card_declined', 'international_fees', 'apr', 'redeem_rewards', 'credit_limit_change', 'damaged_card', 'replacement_card_duration', 'improve_credit_score', 'expiration_date', 'book_flight', 'book_hotel', 'car_rental', 'travel_suggestion', 'travel_alert', 'travel_notification', 'carry_on', 'timezone', 'vaccines', 'flight_status', 'international_visa', 'lost_luggage', 'plug_type', 'exchange_rate', 'direct_deposit', 'pto_request', 'taxes', 'payday', 'pto_balance', 'pto_request_status', 'next_holiday', 'insurance', 'insurance_change', 'schedule_meeting', 'pto_used', 'meeting_schedule', 'income'}:
    # if i:
      new_data.append([i[0], i[1]])

# df = pd.DataFrame(new_data, columns=['text', 'label'])
df = pd.DataFrame(new_data, columns=['text', 'label'])

df

hf_dataset = Dataset.from_pandas(df)
# ru_ds = Dataset.from_pandas(df)

def translate(text):
    """
    Переводит один текст с английского на русский
    """
    # Токенизация
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    # Генерация
    translated = model.generate(
        **inputs,
        max_length=512,
        num_beams=4,  # лучше качество
        early_stopping=True
    )

    # Декодирование
    return tokenizer.decode(translated[0], skip_special_tokens=True)

from tqdm.auto import tqdm

ru_data = []

for item in tqdm(hf_dataset, total=len(hf_dataset), desc="Перевод"):
    translation = translate(item["text"])
    ru_data.append([translation, item["label"]])

print(ru_data)
print(len(ru_data))

ru_df = pd.DataFrame(ru_data, columns=['text', 'label'])
ru_ds = Dataset.from_pandas(ru_df)

print(ru_ds[0])

text = "\n".join(["|".join(item) for item in ru_data])
print(text[:1000])

with open("ru_data_new.txt", "w") as out:
  out.write(text)

# print([item for item in ru_ds])

with open('ru_data.json', 'w', encoding='utf-8') as f:
    json.dump(ru_ds.to_list(), f, ensure_ascii=False, indent=2)

"""## Шумный датасет на русском

"""

# with open("ru_data_new.txt") as readable:
#   dataraw = readable.read()
# ru_data = [list(item.split("|")) for item in dataraw.split("\n")]

from datasets import load_dataset

noise = load_dataset("Den4ikAI/russian_dialogues")

noise['train'][145:150]

len(noise['train'])

noise_frases = []
counter = 0
for item in noise['train']:
  if item['question'] is not None:
    if len(item['question'].split()) < 9:
      noise_frases.append(item['question'])
      counter+=1
    if item['answer'] is not None:
      if len(item['answer'].split()) < 9:
        noise_frases.append(item['answer'])
  if counter == 100000:
    break
del(noise)

random.shuffle(noise_frases)
len(noise_frases)

from collections import defaultdict
shortnoise = []
lengths = defaultdict(list)
for item in noise_frases:
  lengths[len(item.split())].append(item)
  if len(item.split()) in range(0, 3):
    shortnoise.append(item)

print(len(shortnoise))

from typing import Sequence, TypeVar, List

T = TypeVar("T")

def insert_many_random(lst: Sequence[T], inserts: Sequence[T], seed: int | None = None) -> List[T]:
    rnd = random.Random(seed)
    n = len(lst)
    k = len(inserts)

    # позиции 0..n, без повторов
    positions = sorted(rnd.sample(range(n + 1), k))

    out: List[T] = []
    last = 0
    newlabel = []
    for pos, ins in zip(positions, inserts):
        new_ins = ins.split()
        out.extend(lst[last:pos])
        newlabel.extend(["0"]*(pos-last)+["N"]*len(new_ins))
        out.extend(new_ins)
        last = pos
    newlabel += ["0"]*(n-last)
    out.extend(lst[last:])
    return " ".join(out), newlabel

print(insert_many_random(["1", "2", "3", "4", "5"], ["A", "B", "C"], seed=42))

choices = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
p1 = np.array([0.2, 0.1, 0.1, 0.15, 0.15, 0.15, 0.05, 0.05, 0.05])
number = np.random.choice(choices, size=1, p=p1)[0]
number

new_data[0]

seed = 1337
noise_data = []
for item in ru_data:
  oldword = "".join(ch.lower() for ch in item[0] if ch.isalpha() or ch == " ").split()
  needed = []
  numbers = np.array([0, 1, 2, 3, 4])
  p = np.array([0.2, 0.25, 0.25, 0.15, 0.15])
  number = 100
  while number > len(oldword):
    number = np.random.choice(numbers, size=1, p=p)[0]
  choices = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
  p1 = np.array([0.2, 0.1, 0.1, 0.15, 0.15, 0.15, 0.05, 0.05, 0.05])
  length = 10
  while not lengths[length]:
    length = np.random.choice(choices, size=1, p=p1)[0]
  if number != 0:
    for i in range(number):
      newsmth = None
      while newsmth is None:
        newsmth = "".join(ch.lower() for ch in lengths[length].pop() if ch.isalpha() or ch == " ")
      needed.append(newsmth)
    words, label = insert_many_random(oldword, needed, seed=seed)
    noise_data.append([words.split(), label, item[1]])
  else:
    noise_data.append([oldword, ["0"]*len(oldword), item[1]])

noise_df = pd.DataFrame(noise_data, columns=['text', 'label', 'oldlabel'])

noise_df

for item in noise_data:
  if len(item[0]) != len(item[1]):
    print(item[0])
    print(item[1])
    print("\n\n\n")

counter = 0
for item in noise_data:
  if "N" not in item[1]:
    counter+=1
counter

#ensure
for noizzy, original in zip(noise_data, ru_data):
  oldtext = "".join([ch.lower() for ch in original[0] if ch.isalpha() or ch == " "])
  oldtext = oldtext.split()
  newtext = [word for word, label in zip(noizzy[0], noizzy[1]) if label == "0"]
  if oldtext != newtext:
    print(oldtext)
    print(newtext)

noise_df

noise_ds = Dataset.from_pandas(noise_df)
print(noise_ds, "\n", noise_ds[800])

bigarray = []
for item in noise_data:
  bigarray.append("|".join([" ".join(item[0]), " ".join(item[1]), item[2]]))
text = "\n".join(bigarray)
print(text[:1000])

with open("noise_data_new.txt", "w") as out:
  out.write(text)

amounts = []
for item in noise_data:
  counter = 0
  for ch in item[1]:
    if ch == "N":
      counter+=1
  amounts.append(counter)

statistics = defaultdict(int)
for item in amounts:
  statistics[item]+=1
# print("\n".join([f"{k}: {v}" for k, v in statistics.items()]))
print(f"0: {statistics[0]}")
print(f"1-4: {statistics[1]+statistics[2]+statistics[3]+statistics[4]}")
print(f"5-8: {statistics[5]+statistics[6]+statistics[7]+statistics[8]}")
print(f"9-12: {statistics[9]+statistics[10]+statistics[11]+statistics[12]}")
print(f"13-16: {statistics[13]+statistics[14]+statistics[15]+statistics[16]}")
print(f"16+: {sum([v for k, v in statistics.items() if k > 16])}")
print(sum(amounts)/len(amounts))

statistics.keys()

statistics[32]

posstatistics = defaultdict(int)
for item in noise_data:
  for i in range(len(item[1])):
    if item[1][i] == "N":
      if i==len(item):
        posstatistics[-1]+=1
      else:
        posstatistics[i]+=1
print("\n".join([f"{k}: {v}" for k, v in posstatistics.items()]))